# GCP API's
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "etl_application.fullname" . }}-gcp-policy
  labels: {{ include "etl_application.labels" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "etl_application.name" . }}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 199.36.153.4/30
    ports:
    - port: 443
      protocol: TCP
