apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etl_application.name" . }}-gcp-sa-key
  labels: {{ include "etl_application.labels" $ | nindent 4 }}
type: Opaque
data:
  gcpsa.json: {{ .Values.secret.gcpsa.key }}